<div id="home">
    <div class="arow gap margetop bio-desktop">
            <div id="pic" class="column">
                <p class="circle"></p>
            </div>
            <div id="about" class="column">
                <div id="titlebio" class="centered margebottom">
                    <div class="arow">
                        <svg width="20" height="20" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" id="triangle">
                            <polygon points="10,10 90,50 10,90" fill="gold"/>
                        </svg>
                        <h4>&nbsp;LOREM ISPU GNENGEU</h4>
                    </div>
                    <div id="titlefakeborder"></div>
                </div>
                <div id="bio" class="centered smargebottom mb-3">
                    <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ac malesuada tortor. Vivamus cursus fermentum ipsum, vitae sagittis libero ultrices egestas. Proin vel lorem tempus, eleifend arcu ut, vestibulum orci. Maecenas id convallis nisi. Quisque maximus dignissim mi sed volutpat. Vestibulum vitae lacus eleifend turpis commodo egestas. Donec fermentum sapien eget elit faucibus, ac tempor est pharetra. Duis sollicitudin faucibus interdum. Maecenas aliquet efficitur felis, vitae porttitor dui. Nam non dui eu arcu convallis sagittis. 
                    </p>
                </div>
                <div id="embed-confiance" class="ssmargebottom">
                    <p>CEUX QUI M'ONT DÉJÀ FAIT CONFIANCE</p>
                    <div id="subtitlefakeborder"></div>
                </div>
                <div id="clients" class="arow mt-4">
                    <img src="https://yt3.googleusercontent.com/Wpxp_X2eLIUvlZWjUs25npl5DHXooRLCXxIzFdobLuzHWlNLgjwHWk8-GDaqBVMr0lANoJB54A=s160-c-k-c0x00ffffff-no-rj" class="square" onclick="window.open('https://www.youtube.com/@LoannLV')">
                    <img src="https://yt3.googleusercontent.com/ojJONX7Ov2QRB5LoFpwAmM7Oo2-dYivyzPvMDxPr6dW0MgQB-8RtGjPZq5AjEo91ZHgkmHLaZA=s160-c-k-c0x00ffffff-no-rj" class="square" onclick="window.open('https://www.youtube.com/@OUT-0')">
                    <img src="https://yt3.googleusercontent.com/qY-8Xdhrs5Qcn11ye0VklpgSUM3MUL4T3dWfEP1MrcspuFWvi_9MQzpFhB3QGnxvWbEIIrzY7J0=s160-c-k-c0x00ffffff-no-rj" class="square" onclick="window.open('https://www.youtube.com/@skensurvet')">
                    <img src="https://yt3.googleusercontent.com/FhJayyf4SgrVuqpNeVXTVGnZxgGLnHGZnJh_A7uJQkyQ6IfRnFQLJbiProaD5il7fWb-y2LbRw=s160-c-k-c0x00ffffff-no-rj" class="square" onclick="window.open('https://www.youtube.com/@mangatrash')" id="lastsquare">
                </div>
            </div>
    </div>
    <div class="arow gap bio-mobile">
            <div id="pic" class="column">
                <img src="https://creatorspace.imgix.net/users/cljabetdr01wmsv01wgavdti6/ZD4WR5eHH7zDn44x-profile-pic%25202.png?w=300&h=300" class="circle">
            </div>
            <div id="about" class="column ssmargetop">
                <div id="title" class="centered smargebottom">
                    <h2 class="">LOREM ISPU GNENGEU</h2>
                    <div id="mtitlefakeborder"></div> 
                <div id="bio" class="centered ssmargebottom">
                    <p>
                        Le Lorem Ipsum est simplement du faux texte employé  dans la composition et la mise en page avant impression. Le Lorem Ipsum  est le faux texte standard de l'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour  réaliser un livre spécimen
                    </p>
                </div>
                <div id="embed-confiance" class="ssmargebottom centered mauto">
                    <h4 class="">Ceux qui m'ont fait confiance</h4>
                    <div id="msubtitlefakeborder"></div>
                </div>
                <div id="clients" class="arow">
                <img src="https://yt3.googleusercontent.com/Wpxp_X2eLIUvlZWjUs25npl5DHXooRLCXxIzFdobLuzHWlNLgjwHWk8-GDaqBVMr0lANoJB54A=s160-c-k-c0x00ffffff-no-rj" class="square" onclick="window.open('https://www.youtube.com/@LoannLV')">
                <img src="https://yt3.googleusercontent.com/ojJONX7Ov2QRB5LoFpwAmM7Oo2-dYivyzPvMDxPr6dW0MgQB-8RtGjPZq5AjEo91ZHgkmHLaZA=s160-c-k-c0x00ffffff-no-rj" class="square" onclick="window.open('https://www.youtube.com/@OUT-0')">
                    <img src="https://yt3.googleusercontent.com/FhJayyf4SgrVuqpNeVXTVGnZxgGLnHGZnJh_A7uJQkyQ6IfRnFQLJbiProaD5il7fWb-y2LbRw=s160-c-k-c0x00ffffff-no-rj" class="square" onclick="window.open('https://www.youtube.com/@mangatrash')">
                </div>
            </div>
    </div>
</div>



<style>
    .circle {
        background: rgb(166,93,21);
        background: linear-gradient(54deg, rgba(166,93,21,1) 18%, rgba(255,215,0,1) 100%);
        width: 80vh;
        height: 120vh;
        margin-right: 10vh;
        margin-top: -160px;
        margin-left: -90px;
    }
    .square {
        background: grey;
        border-radius: 20%;
        width: 10vh;
        height: 10vh;
        margin: 1vh;
        text-align:center;
        cursor: pointer;
    }
    .arow {
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .column {
        display: flex;
        flex-direction: column;
    }
    .centered {
        text-align: center;
    }
    .gap {
        gap: 1vh;
    }
    .margetop {
        margin-top: 18vh;
    }
    .ssmargetop {
        margin-top: 4vh;
    }
    .margebottom {
        margin-bottom: 10vh;
    }
    .smargebottom {
        margin-bottom: 5vh;
    }
    .ssmargebottom {
        margin-bottom: 2vh;
    }
    .centered {
    text-align: center;
    }
    .mauto {
        margin-left: auto;
        margin-right: auto;
    }
    .gold {
        color: gold;
    }
    .bb-gold {
        border-bottom: gold solid 2px;
        width: fit-content ;
    }
    #titlefakeborder {
        height: 7px;
        background-color: gold;
        width: 80%;
        margin-left: auto;
        margin-right: 20px;
    }
    #subtitlefakeborder {
        height: 4px;
        background-color: gold;
        width: 90%;
        margin-right: auto;
        margin-top: -10px;
    }
    #mtitlefakeborder {
        height: 7px;
        background-color: gold;
        width: 25%;
        margin: 0 auto;
    }
    #msubtitlefakeborder {
        height: 7px;
        background-color: gold;
        width: 90%;
        margin  : 0 auto;
    }
    #home {
        margin-top: -200px;
    }
    #bio {
        text-align: start;
        width: 60%;
        font-size: 22px;
        margin-left: 10vh;
        margin-right: 25vh;
        font-size: large;
    }
    #embed-confiance {
        margin-top: 7vh;
        font-size: smaller;
        text-align: start;
        margin-right: auto;
    }
    #titlebio {
        margin-top: 12vh;
        margin-left: 27vh;
        margin-right: auto ;
    }
    #lastsquare {
        margin-right: 30vh;
    }
    #triangle {
        margin-bottom: 4px;
    }
    @media (min-width: 992px) {
        .bio-mobile {
            display: none;
        }
    }
    @media (max-width: 991px) {
        .bio-desktop {
            display: none;
        }
        .bio-mobile {
            display: block;
            flex-direction: column;
        }
        .circle {
            margin-left:auto;
            margin-right:auto;
            margin-bottom:10px;
        }
        .square {
            background: grey;
            border-radius: 50%;
            width: 10vh;
            height: 10vh;
            margin: 1vh;
            text-align:center;
            cursor: pointer;
        }
    }
</style>