<div id="rowdesktop" class="row container-fluid card-desktop">
    <h2 class="centered gold">Mes stats</h2>
    <p class="centered">Grace a mon travail</p>
    <!--OH LA BELLE CARD-->
    <div id="card" class="card">
        <div id="title">
            <h3 class="centered mt-4 mb-2 bb-gold h1">38M</h3>
        </div>
        <div id="cardbody">
            <div id="content" class="centered mt-3 h5">
                <p>de vue cumulées</p>
            </div>
        </div>
    </div>
        <!--OH LA BELLE CARD-->
    <div id="card" class="card">
        <div id="title">
            <h3 class="centered mt-4 mb-2 bb-gold h1">+181k</h3>
        </div>
        <div id="cardbody">
            <div id="content" class="centered mt-3 h5">
                <p>d'abonnés en tout</p>
            </div>
        </div>
    </div>
        <!--OH LA BELLE CARD-->
    <div id="card" class="card">
        <div id="title">
            <h3 class="centered mt-4 mb-2 bb-gold h1">152</h3>
        </div>
        <div id="cardbody">
            <div id="content" class="centered mt-3 h5">
                <p>vidéos montée en tout</p>
            </div>
        </div>
    </div>
        <!--OH LA BELLE CARD-->
    <div id="card" class="card">
        <div id="title">
            <h3 class="centered mt-4 mb-2 bb-gold h1">87%</h3>
        </div>
        <div id="cardbody">
            <div id="content" class="centered mt-3 h5">
                <p>de taux de click</p>
            </div>
        </div>
    </div>
</div>
<div class="card-mobile">
    <h2 class="centered gold">Mes stats</h2>
    <p class="centered">Grace a mon travail</p>
    <div id="rowdesktop" class="row container-fluid mauto">
        <!--OH LA BELLE CARD-->
        <div id="card" class="card mlauto   ">
            <div id="title">
                <h3 class="centered mt-4 mb-2 bb-gold h1">38M</h3>
            </div>
            <div id="cardbody">
                <div id="content" class="centered mt-3 h5">
                    <p>de vue cumulées</p>
                </div>
            </div>
        </div>
            <!--OH LA BELLE CARD-->
        <div id="card" class="card mrauto">
            <div id="title">
                <h3 class="centered mt-4 mb-2 bb-gold h1">+181k</h3>
            </div>
            <div id="cardbody">
                <div id="content" class="centered mt-3 h5">
                    <p>d'abonnés en tout</p>
                </div>
            </div>
        </div>
    </div>
        <div id="rowdesktop" class="row container-fluid">
            <!--OH LA BELLE CARD-->
            <div id="card" class="card mlauto">
            <div id="title">
                <h3 class="centered mt-4 mb-2 bb-gold h1">152</h3>
            </div>
            <div id="cardbody">
                <div id="content" class="centered mt-3 h5">
                    <p>vidéos montée en tout</p>
                </div>
            </div>
        </div>
            <!--OH LA BELLE CARD-->
        <div id="card" class="card mrauto">
            <div id="title">
                <h3 class="centered mt-4 mb-2 bb-gold h1">87%</h3>
            </div>
            <div id="cardbody">
                <div id="content" class="centered mt-3 h5">
                    <p>de taux de click</p>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    .row{
        flex-direction: row;
        display: flex;
        align-items: center;
        justify-content: space-around;
    }
    .card{
        background: transparent;
        border-style: solid;
        border-width: 2px 2px 2px 2px;
        border-color: black; 
        border-radius: 0.3rem;
        width: 20%;
        height: 20%;
        align-items: center;
        justify-content: space-around;
        margin: 16px;
    }
    .container-fluid{
        margin-left: auto;
        margin-right: auto;
    }
    .mt-4{
        margin-top: 16px;
    }
    .mb-4{
        margin-bottom: 16px;
    }
    .centered {
        text-align: center;
    }
    .gold {
        color: gold;
    }
    h2 {
        width: fit-content;
        margin-left: auto;
        margin-right: auto;
    }
    p {
        margin-left: auto;
        margin-right: auto;
        width: fit-content ;
    }
    i {
        font-size: x-large;
    }
    .bb-gold {
        border-bottom: gold solid 2px;
        width: fit-content ;
    }
    .mlauto {
        margin-left: auto;
        margin-right: auto;
    }
    .mrauto {
        margin-right: auto;
    }
    @media (min-width: 992px) {
        .card-mobile {
            display: none;
        }
    }
    @media (max-width: 991px) {
        .card-desktop {
            display: none;
        }
        .card-mobile {
            display: block;
            flex-direction: row;
        }
        .card {
            width: 40%;
            height: 40%;
        }
        .row {
            justify-content: center;
        }
    }
    @media (max-width: 1243px) {
        .card{
            width: 244px;
            height: 146px;
        }
    }
    @media (max-width: 1128px) {
        .card{
            width: 220px;
            height: 164px;
        }
    }
    @media (max-width: 1032px) {
        .card{
            width: 200px;
            height: 144px;
            margin: 1%;
        }
    }
</style>
