<section id="feedback">
    <div class="container">
        <h2 class="text-center mb-4">Ils témoignent</h2>
        <h3 class="text-center mb-4">Un aperçu de de leur retour exception</h3>
        
        <div id="feedbackcard">
            <div class="row justify-content-center">
                <div class="mx-auto my-2 size"> 
                    <iframe class="rounded-4 size" src="https://www.youtube.com/embed?v=IfZkKaxfJ2s&list=PLacK7rr3zQ_wBxXviOMQ-KNC3uanV_2QW&index=1&controls=0" title="Comment réussir son Winter Arc ?" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
                <div class="mx-auto my-2 size"> 
                    <iframe class="rounded-4 size" src="https://www.youtube.com/embed?v=IfZkKaxfJ2s&list=PLacK7rr3zQ_wBxXviOMQ-KNC3uanV_2QW&index=2&controls=0" title="Comment réussir son Winter Arc ?" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
                <div class="mx-auto my-2 size"> 
                    <iframe class="rounded-4 size" src="https://www.youtube.com/embed?v=IfZkKaxfJ2s&list=PLacK7rr3zQ_wBxXviOMQ-KNC3uanV_2QW&index=3&controls=0" title="Comment réussir son Winter Arc ?" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
                <div class="mx-auto my-2 size"> 
                    <iframe class="rounded-4 size" src="https://www.youtube.com/embed?v=IfZkKaxfJ2s&list=PLacK7rr3zQ_wBxXviOMQ-KNC3uanV_2QW&index=4&controls=0" title="Comment réussir son Winter Arc ?" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
</section>

<style>
    #feedback {
        h2 {
            color: #FFD700;
        }

    }

    #feedbackcard {
        .size {
            width: 280px;
            height: 500px;
        }

        iframe {
            margin-left: -12px;
        }
        
        @media (max-width:768px){

            .size {
                width: 200px;
                height: 450px;
            }
            
        }
    }

</style>