<footer class="pt-3 pb-3">
    <div id="copyright" class="container-fluid centered">
        <h5>Copyright © 2024 All Rights Reserved by Wassim Bouridah.</h5>
        <div id="linktree">
            <ul class="navbar-nav mr-auto" id="socials">
                <li class="nav-item" onclick="window.open('https://www.youtube.com/@wassim.b.h', '_blank')" id="ytb"><i class="ri-youtube-line mx-1"></i></li>
                <li class="nav-item" onclick="window.open('https://www.instagram.com/wassim.bouridah/', '_blank')" id="insta"><i class="ri-instagram-line mx-1"></i></li>
            </ul>
        </div>
    </div>
</footer>

<style>
    #copyrirht { 
        display: flex;
        align-items: center;
    }
    footer {
        background-color: #F0F0F0;
        height: 120px ;
    }
    footer .centered {
        text-align: center;
    }
    footer #socials {
        display: flex;
        flex-direction: row;
        justify-content: center;
    }
    footer li {
        cursor: pointer;
        transition: 0.3s;
    }
    footer li:hover {
        color: gold ;
    }
    footer li {
        font-size: xx-large;
    }
</style>