<section id="formContact">
    <div class="container">
        <div class="row justify-content-center">
            <h4 class="text-center mb-4">CONTACTEZ-MOI !</h4>
            <p class="text-center mb-4">Contactez-moi pour votre prochain projet</p>
    
            <form action="https://formspree.io/f/mwpkozbw" method="post" class="mb-3 col-md-6">
                <input type="text" class="form-control border mb-3" name="nom_prenom" placeholder="Nom Prénom / Nom de la Société" required>
                <input type="email" class="form-control border mb-3" name="email" placeholder="Email" required>
                <input type="tel" class="form-control border mb-3" name="telephone" placeholder="Téléphone">
                <input type="text" class="form-control border  mb-3" name="reseaux" placeholder="Réseaux Sociaux" required>
                <textarea class="form-control border mb-3" rows="5" name="info" placeholder="Détaillez votre projet" required></textarea>
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-warning text-center">Envoyer</button>
                </div>
            </form>
        </div>
    </div>
</section>


<style>
    #formContact {
        h4 {
            color: #FFD700;
        }

        button {
            color: #FFD700;
            border-color: #FFD700;
            font-size: 1.15rem;
            padding: 8px 15px;
            border: 2px solid;
        }

        button:hover {
            color: white;
        }

        @media (max-width: 1200px) {
            .col-md-6 {
                width: 65%;
            }
        }

        @media (max-width: 992px) {
            .col-md-6 {
                width: 75%;
            }
        }

        @media (max-width: 767px) {
            .col-md-6 {
                width: 90%;
            }
        }

    }
</style>