<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top mt-4">
    <div class="container-fluid">
        <a class="navbar-brand anchor" data-index="0" id="title">
            WASSIM BOURIDAH
            <div id="fakeborder"></div>
        </a>
        <div class="collapse navbar-collapse justify-content-start" id="navbarNav">
            <ul class="navbar-nav mr-auto align-items-start">
                <li class="nav-item gap anchor" data-index="0">Accueil</li>
                <li class="nav-item gap anchor" data-index="1">Stats</li>
                <li class="nav-item gap anchor" data-index="2">Portfolio</li>
                <li class="nav-item gap anchor" data-index="3">Feedback</li>
                <li class="nav-item gap anchor" data-index="4">Contact</li>
            </ul>
        </div>
        <div class="justify-content-end">
                <ul class="navbar-nav mr-auto" id="socials">
                    <li class="nav-item" onclick="window.open('https://www.youtube.com/@wassim.b.h', '_blank')" id="ytb"><i class="ri-youtube-line "></i></li>
                    <li class="nav-item" onclick="window.open('https://www.instagram.com/wassim.bouridah/', '_blank')" id="insta"><i class="ri-instagram-line "></i></li>
                    <li class="nav-item" onclick="window.open('https://www.instagram.com/wassim.bouridah/', '_blank')" id="lastli"><i class="ri-tiktok-fill"></i>
                </ul>
        </div>
    </div>
</nav>

<style>
    nav {
        box-shadow: 5px 5px 15px 5px rgba(0,0,0,0.25);
        border-radius: 10px;
        width: 95%;
        height: 70px;
        margin: 0 auto;
    }
    nav li {
        cursor: pointer;
        transition: 0.3s;
        font-size: large;
    }
    nav li:hover {
        color: gold ;
    }
    nav .gap{
        margin-left:1.5vh;
        margin-right:1.5vh;
    }
    .bb-gold {
        border-bottom: gold solid 2px;
        width: fit-content; 
    }
    nav #socials {
        display: flex;
        flex-direction: row;
    }

    nav a:hover {
        color: gold ;
    }
    nav #title {
        margin-left: 4vh;
        margin-right: 7vh;
        height: fit-content;
        padding: 12px 0;
        cursor: pointer;
    }
    nav #fakeborder {
        height: 4px;
        background-color: gold;
        width: 80%;
        margin: 0 auto;
    }
    #lastli {
        margin-right: 4vh;
    }
    nav i {
        cursor: pointer;
        color: black;
        transition: 0.3s;
    }
    nav i:hover {
        color: gold ;
    }
    #insta {
        margin-right: 1vh;
    }
    #ytb {
        margin-right: 1vh;
    }
    nav i {
        font-size: medium;
    }
    @media (max-width: 992px) {
        i {
            display: inline;
            font-size: xx-large;
        }
        nav {
            height: fit-content;
            padding: 12px 0;
        }
        #ytb {
            margin-left: 12px;
        }
        #navbarNav {
            display: none;
        }
    }
</style>