<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand bb-gold" href="#">
            Wassim Bouridha
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item gap different" onclick="window.open('#')">Portfolio</li>
                <li class="nav-item gap" onclick="window.open('#')">Contact</li>
            </ul>
            <div class="navbar-collapse justify-content-end">
                <ul class="navbar-nav mr-auto" id="socials">
                    <li class="nav-item" onclick="window.open('https://www.youtube.com/@wassim.b.h', '_blank')" id="ytb"><i class="ri-youtube-line mx-1"></i></li>
                    <li class="nav-item" onclick="window.open('https://www.instagram.com/wassim.bouridah/', '_blank')" id="insta"><i class="ri-instagram-line mx-1"></i></li>
                </ul>
            </div>
        </div>
    </div>
</nav>

<style>
    nav {
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }
    nav i {
        cursor: pointer;
        font-size: x-large;
    }
    nav li {
        cursor: pointer;
        transition: 0.3s;
    }
    nav li:hover {
        color: gold ;
    }
    #nav {
        height: 60px;
    }
    nav .gap{
        margin-left:0.5vh;
        margin-right: 0.5vh;
    }
    .bb-gold {
        border-bottom: gold solid 2px;
    }
    nav #socials {
        display: flex;
        flex-direction: row;
    }
    @media (max-width: 992px) {
        i {
            display: block;
        }
    }
</style>