<h2 class="centered gold">Titre</h2>
<p class="centered">Description Phrase Accroche Ou Autre</p>

<style>
    .centered {
        text-align: center;
    }
    .gold {
        color: gold;
    }
    h2 {
        width: fit-content;
        margin-left: auto;
        margin-right: auto;
    }
    p {
        margin-left: auto;
        margin-right: auto;
        width: fit-content ;
    }
</style>