<section id="portfolio">
    <div class="container">
        <h4 class="text-center mb-4">MES CRÉATIONS</h4>
        <p class="text-center mb-4">Montages créatifs pour un engagement réel</p>
        
        <div id="videocard">
            <div class="row justify-content-center">
                <div class="mx-auto my-2 size"> 
                    <iframe class="rounded-4 size" src="https://www.youtube.com/embed?v=m29o_0OjJO4&list=PLacK7rr3zQ_xS6p08Lp0U8svwSSuJSHiA&index=1&controls=0" title="Comment réussir son Winter Arc ?" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                    <div class="stat">
                        45k
                    </div>
                </div>
                <div class="mx-auto my-2 size"> 
                    <iframe class="rounded-4 size" src="https://www.youtube.com/embed?v=FGNkC0Eo4GM&list=PLacK7rr3zQ_xS6p08Lp0U8svwSSuJSHiA&index=12&controls=0" title="Comment réussir son Winter Arc ?" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                    <div class="stat">
                        1M
                    </div>
                </div>
                <div class="mx-auto my-2 size"> 
                    <iframe class="rounded-4 size" src="https://www.youtube.com/embed/2KaodPm3VA4?controls=0" title="Comment réussir son Winter Arc ?" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                    <div class="stat">
                        136k
                    </div>
                </div>
                <div class="mx-auto my-2 size"> 
                    <iframe class="rounded-4 size" src="https://www.youtube.com/embed/zj-B0zYBks4?controls=0" title="Comment réussir son Winter Arc ?" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                    <div class="stat">
                        77k
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>



<style>
    #portfolio {
        h4 {
            color: #FFD700;
        }

    }

    #videocard {
        .size {
            width: 280px;
            height: 500px;
        }

        iframe {
            margin-left: -12px;
        }

        .stat {
            margin-top: -50px;
            margin-left: 10px;
            color: white ;
            font-size: 25px;
            font-weight: 600;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.7);
        }
        
        @media (max-width:768px){

            .size {
                width: 200px;
                height: 450px;
            }
            
        }
    }

</style>

